name: calculator_admin
description: "Admin for calculator"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_database: ^10.4.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  formz: ^0.6.1
  equatable: ^2.0.5
  flow_builder: ^0.0.10
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_bloc: ^8.1.3
  intl: ^0.19.0
  jiffy: ^6.2.2
  crypto: ^3.0.3
  meta: ^1.10.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_auth_platform_interface: ^7.0.9
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/fcb-calculator.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/fcb-calculator.png
    - assets/splash.png
    - assets/profile-bg.png